In [3]:
import numpy as np

In [6]:
#1

x = np.arange(10,21)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [10]:
#2

x_flip = np.flip(x) 
print(x_flip)

[20 19 18 17 16 15 14 13 12 11 10]


In [94]:
#3

y = np.arange(4).reshape((2,2))
print(y)

[[0 1]
 [2 3]]


In [2]:
#4

r = np.random.randint(10, size =(4,4,4))
print(r)

NameError: name 'np' is not defined

In [33]:
#5

three = np.random.randint(10, size = (3,3))
print(three)

print('max:', np.max(three))
print('min:', np.min(three))


[[9 4 6]
 [2 6 7]
 [8 8 9]]
max: 9
min: 2


In [178]:
#6

a = np.zeros((8,8),dtype=int)

a[::2,1::2] = 1
a[1::2,::2] = 1

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [183]:
#7

b = np.array([-2,-6,3,9,-4,7])
b_abs = np.abs(b)
b_max = np.max(b_abs)

print(b)
print(b_abs)
print('max:', b_max)

b_replace = np.where(b_replace == b_max, 0, b_replace)

print(b_replace)

[-2 -6  3  9 -4  7]
[2 6 3 9 4 7]
max: 9
[2 6 3 0 4 7]


In [140]:
#8 

c = np.random.randint(10, size = (4,4))


In [145]:
print(c)

c_slice = c[:2,:3]
print()
print(c_slice)

[[  4   8 100   5]
 [  9   2   9   1]
 [  9   8   5   8]
 [  2   9   3   5]]

[[  4   8 100]
 [  9   2   9]]


In [146]:
print(c)

c_slice_2 = c[::,::2]
print()
print(c_slice_2)

[[  4   8 100   5]
 [  9   2   9   1]
 [  9   8   5   8]
 [  2   9   3   5]]

[[  4 100]
 [  9   9]
 [  9   5]
 [  2   3]]


In [147]:
print(c)

c_slice_2[0,1] = 100
print()
print(c_slice_2)


[[  4   8 100   5]
 [  9   2   9   1]
 [  9   8   5   8]
 [  2   9   3   5]]

[[  4 100]
 [  9   9]
 [  9   5]
 [  2   3]]


In [148]:
print(c)

c_slice_copy = c[::, ::2].copy()

c_slice_copy[0,1] = 50
print()
print(c_slice_copy)

[[  4   8 100   5]
 [  9   2   9   1]
 [  9   8   5   8]
 [  2   9   3   5]]

[[ 4 50]
 [ 9  9]
 [ 9  5]
 [ 2  3]]


In [150]:
#9

d = np.random.randint(10, size = (3,3))
e = np.random.randint(10, size = (3,3))

In [156]:
print(d)
print()
print(e)

[[7 5 1]
 [0 8 0]
 [8 1 1]]

[[2 5 7]
 [7 4 9]
 [0 4 2]]


In [159]:
de_hor = np.concatenate([d,e])
print(de_hor)

[[7 5 1]
 [0 8 0]
 [8 1 1]
 [2 5 7]
 [7 4 9]
 [0 4 2]]


In [160]:
de_ver = np.concatenate([d,e], axis=1)
print(de_ver)

[[7 5 1 2 5 7]
 [0 8 0 7 4 9]
 [8 1 1 0 4 2]]


In [161]:
de_vstack = np.vstack([d,e])
print(de_vstack)

[[7 5 1]
 [0 8 0]
 [8 1 1]
 [2 5 7]
 [7 4 9]
 [0 4 2]]


In [162]:
de_hstack = np.hstack([d,e])
print(de_hstack)

[[7 5 1 2 5 7]
 [0 8 0 7 4 9]
 [8 1 1 0 4 2]]


In [165]:
#10

g = np.random.randint(10, size = (6,6))
print(g)

[[1 5 8 6 0 5]
 [6 6 7 7 2 9]
 [0 7 3 0 8 5]
 [3 0 2 3 7 5]
 [1 3 8 7 5 4]
 [3 6 1 0 2 8]]


In [166]:
g1,g2 = np.vsplit(g, [3])

print(g1)
print()
print(g2)

[[1 5 8 6 0 5]
 [6 6 7 7 2 9]
 [0 7 3 0 8 5]]

[[3 0 2 3 7 5]
 [1 3 8 7 5 4]
 [3 6 1 0 2 8]]


In [167]:
g3,g4 = np.hsplit(g, [3])

print(g3)
print()
print(g4)

[[1 5 8]
 [6 6 7]
 [0 7 3]
 [3 0 2]
 [1 3 8]
 [3 6 1]]

[[6 0 5]
 [7 2 9]
 [0 8 5]
 [3 7 5]
 [7 5 4]
 [0 2 8]]
